name: tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository under $GITHUB_WORKSPACE.
    - name: Checkout vls
      uses: actions/checkout@v2
      with:
        path: vls

    - name: Checkout vparse
      uses: actions/checkout@v2
      with:
        repository: 'sthenic/vparse'
        path: vparse

    - name: Checkout vltoml
      uses: actions/checkout@v2
      with:
        repository: 'sthenic/vltoml'
        path: vltoml

    - name: Checkout vlint
      uses: actions/checkout@v2
      with:
        repository: 'sthenic/vlint'
        path: vlint
        token: ${{ secrets.TOKEN }}

    # Manually choose a patched fork of parsetoml until the library is fixed.
    - name: Checkout parsetoml
      uses: actions/checkout@v2
      with:
        repository: 'sthenic/parsetoml'
        path: parsetoml

    - uses: jiro4989/setup-nim-action@v1.1.4
      with:
        nim-version: 'stable'

    - name: Install vparse, vltoml and vlint
      run: |
        pushd parsetoml
        nimble install -y
        popd
        pushd vparse
        nimble install -y
        popd
        pushd vltoml
        nimble install -y
        popd
        pushd vlint
        nimble install -y
        popd

    - name: Build
      run: |
        cd vls
        nimble build -y

    - name: Test
      run: |
        cd vls
        nimble test -y
