name: Run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository under $GITHUB_WORKSPACE.
    - name: Checkout vls
      uses: actions/checkout@v2
      with:
        path: vls

    - name: Checkout vparse
      uses: actions/checkout@v2
      with:
        repository: 'sthenic/vparse'
        path: vparse
        token: ${{ secrets.VPARSE_TOKEN }}

    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v2
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-stable

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v2
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-stable

    - uses: jiro4989/setup-nim-action@v1.1.2
      with:
        nim-version: '1.2.0'

    - name: Install vparse
      run: |
        cd vparse
        nimble install -y

    - name: Build
      run: |
        cd vls
        nimble build -y

    - name: Test
      run: |
        cd vls
        nimble test -y
