name: release
on:
  push:
    tags:
      - 'v*'

env:
  VLS_VERSION:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
    steps:
    # Check out the repository under $GITHUB_WORKSPACE.
    - name: Checkout vls
      uses: actions/checkout@v2
      with:
        path: vls

    - name: Checkout vparse
      uses: actions/checkout@v2
      with:
        repository: 'sthenic/vparse'
        path: vparse
        token: ${{ secrets.VPARSE_TOKEN }}

    - name: Checkout vltoml
      uses: actions/checkout@v2
      with:
        repository: 'sthenic/vltoml'
        path: vltoml
        token: ${{ secrets.VPARSE_TOKEN }}

    - uses: jiro4989/setup-nim-action@v1.1.2
      if: ${{ matrix.os != 'macos-latest' }}
      with:
        nim-version: '1.2.4'

    - name: 'Install Nim on macOS'
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        sh init.sh -y

    - name: Install vparse and vltoml
      run: |
        pushd vparse
        nimble install -y
        popd
        pushd vltoml
        nimble install -y
        popd

    - name: Build Ubuntu
      if: ${{ matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-16.04'}}
      run: |
        cd vls
        nimble build -y
        source /etc/os-release
        PLATFORM_INFO="${ID}-${VERSION_ID}-$(uname -i)"
        ARCHIVE_FILENAME="vls-$(cat src/VERSION)-${PLATFORM_INFO}"
        cd build
        sh build_deb.sh "${PLATFORM_INFO}"
        cp *.deb ../
        cd ..
        tar -czf "${ARCHIVE_FILENAME}.tar.gz" vls LICENSE THIRD_PARTY_LICENSES.md CHANGELOG.md
        md5sum "${ARCHIVE_FILENAME}.tar.gz" > ${ARCHIVE_FILENAME}.tar.gz.md5
        md5sum "${ARCHIVE_FILENAME}.deb" > ${ARCHIVE_FILENAME}.deb.md5

    - name: Build macOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        cd vls
        nimble build -y
        ARCHIVE_FILENAME="vls-$(cat src/VERSION)-macos"
        tar -czf "${ARCHIVE_FILENAME}.tar.gz" vls LICENSE THIRD_PARTY_LICENSES.md CHANGELOG.md
        md5 "${ARCHIVE_FILENAME}.tar.gz" > ${ARCHIVE_FILENAME}.tar.gz.md5

    - name: Upload artifacts
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.VPARSE_TOKEN }}
      with:
        files: |
          vls/*.tar.gz
          vls/*.tar.gz.md5
          vls/*.deb
          vls/*.deb.md5
