name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
          - windows-latest
          - macos-latest
    steps:
    - name: Checkout vls
      uses: actions/checkout@v2
      with:
        path: vls

    - name: Checkout vparse
      uses: actions/checkout@v2
      with:
        repository: 'sthenic/vparse'
        path: vparse

    - name: Checkout vltoml
      uses: actions/checkout@v2
      with:
        repository: 'sthenic/vltoml'
        path: vltoml

    # Manually choose a patched fork of parsetoml until the library is fixed.
    - name: Checkout parsetoml
      uses: actions/checkout@v2
      with:
        repository: 'sthenic/parsetoml'
        path: parsetoml

    - uses: jiro4989/setup-nim-action@v1.1.2
      with:
        nim-version: 'stable'

    - name: Install vparse and vltoml
      run: |
        pushd parsetoml
        nimble install -y
        popd
        pushd vparse
        nimble install -y
        popd
        pushd vltoml
        nimble install -y
        popd

    - name: Build Ubuntu
      if: ${{ matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-16.04'}}
      run: |
        cd vls
        nimble build -y
        source /etc/os-release
        PLATFORM_INFO="${ID}-${VERSION_ID}-$(uname -i)"
        ARCHIVE_FILENAME="vls-$(cat src/VERSION)-${PLATFORM_INFO}"
        cd build
        sh build_deb.sh "${PLATFORM_INFO}"
        cp *.deb ../
        cd ..
        tar -czf "${ARCHIVE_FILENAME}.tar.gz" vls README.md LICENSE THIRD_PARTY_LICENSES.md CHANGELOG.md
        md5sum "${ARCHIVE_FILENAME}.tar.gz" > ${ARCHIVE_FILENAME}.tar.gz.md5
        md5sum "${ARCHIVE_FILENAME}.deb" > ${ARCHIVE_FILENAME}.deb.md5

    - name: Build macOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        cd vls
        nimble build -y
        ARCHIVE_FILENAME="vls-$(cat src/VERSION)-macos"
        tar -czf "${ARCHIVE_FILENAME}.tar.gz" vls README.md LICENSE THIRD_PARTY_LICENSES.md CHANGELOG.md
        md5 "${ARCHIVE_FILENAME}.tar.gz" > ${ARCHIVE_FILENAME}.tar.gz.md5

    - name: Build Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        cd vls
        nimble build -y
        $ARCHIVE_FILENAME="vls-$(cat src/VERSION)-win_x86_64"
        7z a -tzip "${ARCHIVE_FILENAME}.zip" vls.exe README.md LICENSE THIRD_PARTY_LICENSES.md CHANGELOG.md
        [string]$MD5 = (get-filehash -Algorithm MD5 "${ARCHIVE_FILENAME}.zip").Hash
        echo $MD5 > "${ARCHIVE_FILENAME}.zip.md5"

    - name: Upload artifacts
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        files: |
          vls/*.tar.gz
          vls/*.tar.gz.md5
          vls/*.deb
          vls/*.deb.md5
          vls/*.zip
          vls/*.zip.md5
